version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    commit-message:
      prefix: 'chore'
    open-pull-requests-limit: 5
