name: Setup Sanity Env
description: Shared steps to set up Node, Bun, and install dependencies

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.4.1'

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.1.38'

    - name: Install Dependencies
      run: bun install
      shell: bash
