name: Setup Sanity Env
description: Shared steps to set up Node, Bun, and install dependencies

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.18.0'

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.2.19'

    - name: Install Dependencies
      run: bun install
      shell: bash
