name: neon-drizzle.sanity.studio

on:
  push:
    branches:
      - main

jobs:
  deploy-sanity:
    runs-on: ubuntu-latest
    env:
      # Use a job-level env variable to store the secret value
      SANITY_STUDIO_HOSTNAME_PROD: ${{ secrets.SANITY_STUDIO_HOSTNAME_PROD }}
    steps:
      - name: Call reusable workflow for PROD studio
        uses: ./.github/workflows/deploy-sanity.yaml
        with:
          # Pass the environment variable to the input
          studio_hostname: ${{ env.SANITY_STUDIO_HOSTNAME_PROD }}
