name: Deploy Sanity (mjm-llc.sanity.studio) on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy-sanity-schema:
    name: Deploy Sanity Schema
    runs-on: ubuntu-latest

    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}

    steps:
      - uses: ./.github/actions/setup-sanity

      - name: Deploy Sanity Schema
        run: npx sanity schema deploy --non-interactive
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}

  deploy-sanity-studio:
    name: Deploy Sanity Studio
    runs-on: ubuntu-latest
    needs: deploy-sanity-schema

    env:
      SANITY_STUDIO_HOSTNAME: ${{ secrets.SANITY_STUDIO_HOSTNAME_PROD }}
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}

    steps:
      - uses: ./.github/actions/setup-sanity

      - name: Deploy Sanity Studio
        run: bun run sanity deploy --non-interactive
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}
