name: neon-drizzle-fe-dev.sanity.studio

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  actions: write

jobs:
  deploy-sanity:
    uses: ./.github/workflows/deploy-sanity.yaml
    secrets:
      SANITY_STUDIO_HOSTNAME: ${{ secrets.SANITY_STUDIO_HOSTNAME_DEV }}
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_API_DEPLOY_TOKEN }}
