name: Create Vercel Preview URL on Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}

      - name: Comment Preview Link on PR
        uses: actions/github-script@v6
        with:
          script: |
            const previewUrl = `🚀 **Vercel Preview URL**: [${{ steps.vercel-deploy.outputs.preview-url }}](${{ steps.vercel-deploy.outputs.preview-url }})`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: previewUrl
            });
